# Docker Compose 配置 - 用于部署前端应用和Nginx
version: '3.8'

services:
  # 前端应用 + Nginx 反向代理
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      # 挂载构建后的前端文件
      - ./dist:/usr/share/nginx/html
      # 挂载Nginx配置文件
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # 挂载日志目录（可选）
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend-api
      - workflow-api
    restart: unless-stopped
    
  # 模拟后端API服务 (1207端口)
  backend-api:
    image: openjdk:11-jre-slim
    ports:
      - "1207:1207"
    # 这里需要替换为您实际的Java应用启动命令
    command: ["echo", "请替换为实际的Java应用启动命令"]
    restart: unless-stopped
    
  # 模拟工作流API服务 (1202端口)  
  workflow-api:
    image: openjdk:11-jre-slim
    ports:
      - "1202:1202"
    # 这里需要替换为您实际的Java应用启动命令
    command: ["echo", "请替换为实际的Java应用启动命令"]
    restart: unless-stopped

# 网络配置
networks:
  default:
    driver: bridge